#!/usr/bin/env bash
# Based on script from https://github.com/jackdb/pg-app-dev-vm/blob/master/Vagrant-setup/bootstrap.sh

set -e

curl https://raw.githubusercontent.com/IgnisDa/printr/main/get-printr.sh | sh -s -- --yes

# Edit the following to change the version of PostgreSQL that is installed
PG_VERSION=13

PG_REPO_APT_SOURCE=/etc/apt/sources.list.d/pgdg.list
if [ ! -f "$PG_REPO_APT_SOURCE" ]
then
  # Add PG apt repo:
  echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > "$PG_REPO_APT_SOURCE"
  # Add PGDG repo key:
  wget --quiet -O - https://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | apt-key add -
fi

export DEBIAN_FRONTEND=noninteractive

PROVISIONED_ON=/etc/vm_provision_on_timestamp
if [ -f "$PROVISIONED_ON" ]
then
  printr -c red "
  VM was already provisioned at: $(cat $PROVISIONED_ON)
  To run system updates manually login via 'vagrant ssh' and run 'apt-get update
"
  exit
fi

printr -c cyan -f bold "Adding apt-keys and installing environment packages"

# Get installer for nodejs
curl -sL https://deb.nodesource.com/setup_15.x | bash -
# get installer for yarn
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
# Update package list
apt-get update
# install heroku to the system
wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh

# Install postgresql, python3.9 and fish shell (required for development)
apt-get -y install "yarn" "bat" "fish" "nodejs" "gcc" "g++" "make" "postgresql-$PG_VERSION" "postgresql-contrib-$PG_VERSION" "exa" "neovim" "python3" "python3-pip" "openjdk-15-jdk" "openjdk-15-jre" "maven"

printr -c yellow -f bold "Environment packages installed successfully!"

PG_CONF="/etc/postgresql/$PG_VERSION/main/postgresql.conf"
PG_HBA="/etc/postgresql/$PG_VERSION/main/pg_hba.conf"
PG_DIR="/var/lib/postgresql/$PG_VERSION/main"

# Edit postgresql.conf to change listen address to '*':
sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" "$PG_CONF"

# Append to pg_hba.conf to add password auth:
echo "host    all             all             all                     md5" >> "$PG_HBA"

# Explicitly set default client_encoding
echo "client_encoding = utf8" >> "$PG_CONF"

# Restart so that all new config is loaded:
service postgresql restart

DB_PASSWORD=password
DB_USER=username
DB_DATABASE=server_db
ROOT_USER=postgres

su - $ROOT_USER -c "/home/vagrant/Resourceium/tools/init-db.sh $DB_PASSWORD $DB_DATABASE $DB_USER $ROOT_USER"

echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
sudo sysctl -p

# Tag the provision time:
timedatectl set-ntp true
timedatectl set-timezone Asia/Kolkata
date > "$PROVISIONED_ON"

pip3 install poetry

printr -c blue -f bold "
Successfully created Resourceium development virtual machine
"
