# Generated by Django 3.1.5 on 2021-05-02 17:51

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='user_id',
            field=models.IntegerField(default=1, help_text='The id of the user this file belongs to'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(help_text='The actual file that is uploaded', upload_to=files.models.get_upload_directory),
        ),
    ]
