# Generated by Django 3.1.5 on 2021-05-03 03:14

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20210502_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='folder_id',
            field=models.IntegerField(default=1, help_text='The id of the folder this file belongs to.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='name',
            field=models.TextField(default='hello', help_text='The name of the file that was uploaded.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(help_text='The actual file that is uploaded.', upload_to=files.models.get_upload_directory),
        ),
        migrations.AlterField(
            model_name='upload',
            name='user_id',
            field=models.IntegerField(help_text='The id of the user this file belongs to.'),
        ),
    ]
