#!/usr/bin/env bash
# This script will be used to install dependencies for all the fictitious applications

curl https://raw.githubusercontent.com/IgnisDa/printr/main/get-printr.sh | sh -s -- --yes

# setup the git identities
git config --global user.name "Diptesh Choudhuri"
git config --global user.email "ignisda2001@gmail.com"

# remove the default fish shell prompt
set fish_greeting

# install Gitzer to the system
curl -sSL https://raw.githubusercontent.com/IgnisDa/Gitzer/main/get-gitzer.py | python3

# load all my system configs
rm -rf $HOME/.config
git clone https://github.com/IgnisDa/linux-configs.git $HOME/.config

# use the starship prompt
curl -fsSL https://starship.rs/install.sh > /tmp/install.sh
chmod +x /tmp/install.sh
/tmp/install.sh --force

# set the default interactive shell as fish
rm -rf "$HOME/.bashrc"
ln -s "$HOME/.config/.bashrc" "$HOME/.bashrc"

curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/bin

sudo pip install poetry

backend_folder="server"
frontend_folder="client"
storage_folder="storage"

# Install the dependencies of each micro-service

PROJECT_FOLDER="/workspace/Resourceium"
cd "$PROJECT_FOLDER"
cd "$backend_folder"
sudo chown -R vscode:vscode $HOME/.m2/repository
mvn dependency:go-offline -B --fail-never

cd "$PROJECT_FOLDER"
cd "$frontend_folder"
yarn install

cd "$PROJECT_FOLDER"
cd "$storage_folder"
poetry config virtualenvs.in-project "true"
poetry install -v
