#!/usr/bin/env bash
# This script will be used to install dependencies for all the resourceium applications

# setup the git identities
git config --global user.name "${GIT_AUTHOR_NAME}"
git config --global user.email "${GIT_AUTHOR_EMAIL}"

# remove the default fish shell prompt
set fish_greeting

# load all my system configs
sudo rm -rf $HOME/.config
git clone https://github.com/IgnisDa/linux-configs.git $HOME/.config
sudo chown -R $USERNAME:$USERNAME $HOME/.config
sudo mkdir -p $HOME/.m2
sudo chown -R  $USERNAME:$USERNAME $HOME/.m2

# set the default interactive shell as fish
rm -rf "$HOME/.bashrc"
ln -s "$HOME/.config/.bashrc" "$HOME/.bashrc"

# Install the dependencies of each micro-service
PROJECT_FOLDER="/workspace/Resourceium"
just setup
