#!/usr/bin/env bash
# This script will be used to install dependencies for all the fictitious applications

# setup the git identities
git config --global user.name "Diptesh Choudhuri"
git config --global user.email "ignisda2001@gmail.com"

# remove the default fish shell prompt
set fish_greeting

# load all my system configs
sudo rm -rf $HOME/.config
git clone https://github.com/IgnisDa/linux-configs.git $HOME/.config
sudo chown -R $USERNAME:$USERNAME $HOME/.config

# set the default interactive shell as fish
rm -rf "$HOME/.bashrc"
ln -s "$HOME/.config/.bashrc" "$HOME/.bashrc"

# Install the dependencies of each micro-service
PROJECT_FOLDER="/workspace/Resourceium"
just setup
