#!/usr/bin/env bash

set -e
set -u

PASSWORD="admin-password"

DB_1="server_db"
DB_2="website-db"

USER="username"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" << SQL_COMMANDS
-- Database for the server->
DROP DATABASE if exists "$DB_1";
-- Create the database user:
CREATE ROLE "$USER" WITH LOGIN CREATEDB ENCRYPTED PASSWORD '$PASSWORD';
-- Create the database:
CREATE DATABASE "$DB_1" WITH OWNER="$USER"
                                  LC_COLLATE="en_US.utf8"
                                  LC_CTYPE="en_US.utf8"
                                  ENCODING="UTF8"
                                  TEMPLATE=template0;
-- Grant necessary privileges
GRANT ALL PRIVILEGES ON DATABASE "$DB_1" TO "$USER";

-- Database for the server->
DROP DATABASE if exists "$DB_2";
-- Create the database:
CREATE DATABASE "$DB_2" WITH OWNER="$USER"
                                  LC_COLLATE="en_US.utf8"
                                  LC_CTYPE="en_US.utf8"
                                  ENCODING="UTF8"
                                  TEMPLATE=template0;
-- Grant necessary privileges
GRANT ALL PRIVILEGES ON DATABASE "$DB_2" TO "$USER";
SQL_COMMANDS
