#!/usr/bin/env bash

PASSWORD="${MYSQL_PASSWORD}"

MAIN_DB="${MYSQL_DATABASE}"

DB_USER="${MYSQL_USER}"

mysql -u root <<MYSQL_SCRIPT
CREATE DATABASE $MAIN_DB;

CREATE USER '${DB_USER}'@'localhost' IDENTIFIED BY '${PASSWORD}';
GRANT ALL PRIVILEGES ON ${MAIN_DB}.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;
MYSQL_SCRIPT
