#!/usr/bin/env bash
# This script will be used to spin up the development servers for all the Resourceium applications

# directory path of java development server
backend_folder="server"
# directory path of nuxt development server
frontend_folder="client"
# directory path of django development server
storage_folder="storage"


if command -v gp &>/dev/null;
  then URL="$(gp url 8000)"
  else URL="http://localhost:8000/"
fi

export PIP_USER=false

# Start all the servers
{ cd "$storage_folder" && poetry install && poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8080 & \
  cd "$backend_folder" && mvn spring-boot:run -Dspring-boot.run.profiles=dev & \
  cd "$frontend_folder" && yarn install && API_URL="${URL}" yarn dev; }
