#!/usr/bin/env bash
# This script will be used to spin up the development servers for all the Resourceium applications

# directory path of django development server
backend_folder="server"
# directory path of nuxt development server
frontend_folder="client"

if command -v gp &>/dev/null;
  then URL="$(gp url 8000)"
  else URL="http://localhost:8000/"
fi

# Start all the servers
{ cd "$backend_folder" && mvn spring-boot:run -Dspring-boot.run.profiles=dev,gitpod & \
  cd "$frontend_folder" && yarn install && API_URL="${URL}" yarn dev; }
