#!/usr/bin/env bash
# This script will be used to spin up the development servers for all the Resourceium applications

# directory path of django development server
backend_folder="server"
# directory path of nuxt development server
frontend_folder="client"

# Start all the servers
{ cd "$backend_folder" && mvn spring-boot:run & \
  cd "$frontend_folder" && yarn install && yarn dev; }
